framework:
    messenger:
        failure_transport: failed

        default_bus: command_bus

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            event_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
                    - inbox

        transports:
             failed: 'doctrine://default?table_name=failed_messages&queue_name=failed'

             outbox:
                dsn: 'doctrine://default?table_name=outbox'
                serializer: messenger.transport.symfony_serializer

             order.event.order_created:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%/order.event.order_created'
                 serializer: app.shared.message_bus.serializer.publish_serializer
                 options:
                     exchange:
                         name: order.event.order_created
                     queues: []
             inventory.event.order_created:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%/inventory.event.order_created'
                 serializer: app.shared.message_bus.serializer.consume_serializer
                 options:
                     exchange:
                         name: order.event.order_created
                     queues:
                        inventory.event.order_created: ~
                 retry_strategy:
                     max_retries: 3
                     delay: 1000
        routing:

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
