services:
    php:
        build:
            context: docker/php
        volumes:
            - ".:/app"
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        depends_on:
            - db
            - rabbitmq

    db:
        image: mysql:8.3
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        ports:
            - "3306:3306"

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"
            - "15672:15672"

networks:
    default:
        driver: bridge
